### ISSUE TITLE
Place the configuration documentation into the HELM chart (if possible)

### ISSUE THREAD

**Issue by edwbuck** [spiffe/helm-charts-flex#12]
If possible, place the configuration.md documentation into the helm chart (zip) bundle.

**Comment by kfox1111** [comment]
It has to be in the chart for it to be bundled. So, move it under spire-flex?

**Comment by edwbuck** [comment]
Tha's a great idea.  I'll see if helm package pulls it into the zip.  If it doesn't, I'll see if there is some way to reference it from Chart.yaml, and if that fails, if there's some other way to put documentation of this sort into the chart.

**Comment by kfox1111** [comment]
It will pull in any file in that isn't in the helm ignore file.

Note that, according to my understanding, anything in the package will also be loaded into the k8s cluster as it saves the entire chart into the release secret in k8s. So, use it sparingly.
