### ISSUE TITLE
Add 0.0.0.0 as a supported probe IP address

### ISSUE THREAD

**Issue by edwbuck** [spiffe/helm-charts-flex#3]
We missed an obvious IPv4 address, the alias of 0.0.0.0, currently we only permit "localhost", "127.0.0.1", and "::1"

@kfox1111 Is there a IPv6 equivalent of "0.0.0.0"?

**Comment by kfox1111** [comment]
My ipv6 isn't very good yet. but I think in that case, its "::"

**Comment by edwbuck** [comment]
> My ipv6 isn't very good yet. but I think in that case, its "::"

Seems like you are correct.  I modified the soon-to land PR to include it.
